### ISSUE TITLE
Improve the detail information

### ISSUE THREAD

**Issue by tropicar** [dappnode/DMS#11]
It would be a good idea to include on the description of the package which this package needs the installation of the node_exporter package. User with no technical knowledge doesn't know grafana needs the node exporter metrics to generate the dashboards.
There is a guide, on Spanish and English, on how to set up the DMS, maybe would be nice include the link on the description to make easier the access to the user.

[Guide how to set up tour DMS and node exporter](https://forum.dappnode.io/t/begginer-friendly-install-monitoring-system-on-dappnode-using-dms-package/623)

**Comment by dapplion** [comment]
Maybe the DAPPMANAGER should detect that a package has a dashboard and invite the user to install it
